name: Trigger Workflow in azure-arc-jumpstart-app

on:
  push:
    branches:
      - test-workflow  # Adjust the branch as needed

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN_NEW }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Use the obtained token
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"event_type": "workflow-trigger", "client_payload": {"key": "value"}}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" \
            -H "Authorization: token $GITHUB_TOKEN"

        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
      - uses: actions/github-script@v6
        with:
          github-token: ${{ steps.githubAppAuth.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Fractal-IOTFAL',
              repo: 'childprivaterepos',
              workflow_id: 'test-trigger.yml',
              ref: 'main'
            })
